# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wLEdObiQ36x-hBCaAnhHVkjUQfrY2BVu
"""

import streamlit as st
import pandas as pd
import joblib
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

st.title("Credit Card Default Prediction")

# Load saved models & preprocessor
preprocessor = joblib.load('preprocessor.pkl')
models = joblib.load('models.pkl')

# Upload test CSV
uploaded = st.file_uploader("Upload test CSV (same columns as original)", type="csv")
if uploaded:
    df_test = pd.read_csv(uploaded)
    X_test = df_test.drop(['ID', 'dpnm'], axis=1, errors='ignore')
    y_test = df_test['dpnm'] if 'dpnm' in df_test.columns else None

    X_test_prep = preprocessor.transform(X_test)

    # Model selection
    model_name = st.selectbox("Choose Model", list(models.keys()))
    model = models[model_name]

    y_pred = model.predict(X_test_prep)
    y_prob = model.predict_proba(X_test_prep)[:, 1]

    # Metrics
    st.subheader("Evaluation Metrics")
    acc = (y_pred == y_test).mean() if y_test is not None else None
    auc = roc_auc_score(y_test, y_prob) if y_test is not None else None
    st.write(f"Accuracy: {acc:.4f}")
    st.write(f"AUC: {auc:.4f}")

    # Confusion Matrix
    st.subheader("Confusion Matrix")
    cm = confusion_matrix(y_test, y_pred)
    disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['No Default', 'Default'])
    fig, ax = plt.subplots()
    disp.plot(ax=ax, cmap='Blues')
    st.pyplot(fig)

    # Download predictions
    pred_df = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred, 'Probability': y_prob})
    st.download_button("Download predictions", pred_df.to_csv(index=False), "predictions.csv")