# -*- coding: utf-8 -*-
"""ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xSOVcnVvUcujH4EQhdGVBF-VSQ8QRRWq
"""

import streamlit as st
import pandas as pd
import joblib
import os
from sklearn.metrics import (
    accuracy_score, roc_auc_score, precision_score,
    recall_score, f1_score, matthews_corrcoef, confusion_matrix, ConfusionMatrixDisplay
)
import matplotlib.pyplot as plt

# ────────────────────────────────────────────────────────────────
# Debug: show current directory and files (helpful during deployment)
# ────────────────────────────────────────────────────────────────
st.write("**Debug Info**")
st.write("Current working directory:", os.getcwd())
st.write("Files in current directory:", os.listdir("."))
st.write("Files in 'model' folder:", os.listdir("model") if os.path.exists("model") else "model folder not found")

# ────────────────────────────────────────────────────────────────
# Title
# ────────────────────────────────────────────────────────────────
st.title("Credit Card Default Prediction")

# ────────────────────────────────────────────────────────────────
# Load preprocessor and all models from model/ folder
# ────────────────────────────────────────────────────────────────
try:
    preprocessor = joblib.load('model/preprocessor.pkl')

    models = {
        "Logistic Regression": joblib.load('model/logistic_regression.pkl'),
        "Decision Tree":       joblib.load('model/decision_tree.pkl'),
        "KNN":                 joblib.load('model/knn.pkl'),
        "Naive Bayes":         joblib.load('model/naive_bayes.pkl'),
        "Random Forest":       joblib.load('model/random_forest.pkl'),
        "XGBoost":             joblib.load('model/xgboost.pkl')
    }

    st.success("All models and preprocessor loaded successfully!")
except Exception as e:
    st.error(f"Error loading models: {e}")
    st.stop()

# ────────────────────────────────────────────────────────────────
# File uploader for test data
# ────────────────────────────────────────────────────────────────
st.subheader("Upload Test Data (CSV)")
uploaded_file = st.file_uploader("Choose a CSV file (same structure as original)", type="csv")

if uploaded_file is not None:
    try:
        df_test = pd.read_csv(uploaded_file)
        st.write("Preview of uploaded data:", df_test.head())

        # Prepare features (drop ID and target if present)
        X_test = df_test.drop(columns=['ID', 'default payment next month', 'dpnm'], errors='ignore')

        # Get true labels if available
        y_true = None
        if 'default payment next month' in df_test.columns:
            y_true = df_test['default payment next month']
        elif 'dpnm' in df_test.columns:
            y_true = df_test['dpnm']

        # Preprocess
        X_test_prep = preprocessor.transform(X_test)

        # ────────────────────────────────────────────────────────────────
        # Model selection
        # ────────────────────────────────────────────────────────────────
        selected_model_name = st.selectbox(
            "Select Model",
            list(models.keys())
        )

        selected_model = models[selected_model_name]

        # ────────────────────────────────────────────────────────────────
        # Make predictions
        # ────────────────────────────────────────────────────────────────
        y_pred = selected_model.predict(X_test_prep)
        y_prob = selected_model.predict_proba(X_test_prep)[:, 1]

        # ────────────────────────────────────────────────────────────────
        # Show metrics if true labels are available
        # ────────────────────────────────────────────────────────────────
        if y_true is not None:
            st.subheader("Evaluation Metrics")

            metrics = {
                "Accuracy": accuracy_score(y_true, y_pred),
                "AUC": roc_auc_score(y_true, y_prob),
                "Precision": precision_score(y_true, y_pred, zero_division=0),
                "Recall": recall_score(y_true, y_pred, zero_division=0),
                "F1 Score": f1_score(y_true, y_pred, zero_division=0),
                "MCC": matthews_corrcoef(y_true, y_pred)
            }

            for metric_name, value in metrics.items():
                st.metric(metric_name, f"{value:.4f}")

        # ────────────────────────────────────────────────────────────────
        # Confusion Matrix
        # ────────────────────────────────────────────────────────────────
        st.subheader("Confusion Matrix")
        if y_true is not None:
            cm = confusion_matrix(y_true, y_pred)
            fig, ax = plt.subplots(figsize=(5, 4))
            disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['No Default (0)', 'Default (1)'])
            disp.plot(ax=ax, cmap='Blues')
            st.pyplot(fig)
        else:
            st.info("True labels not found in uploaded file → confusion matrix not available")

        # ────────────────────────────────────────────────────────────────
        # Download predictions
        # ────────────────────────────────────────────────────────────────
        results_df = pd.DataFrame({
            'Predicted': y_pred,
            'Probability of Default': y_prob.round(4)
        })

        if y_true is not None:
            results_df['Actual'] = y_true

        csv = results_df.to_csv(index=False).encode('utf-8')
        st.download_button(
            label="Download Predictions (CSV)",
            data=csv,
            file_name="predictions.csv",
            mime="text/csv"
        )

    except Exception as e:
        st.error(f"Error processing file: {e}")
else:
    st.info("Please upload a test CSV file to start predictions.")